language: node_js
node_js: 8.10.0
env:
  global:
    - CLOUD_BUCKET: rido-zaen
    - secure: L6Hp+0l36UeN763knbNn5DbxwtiK/4uydOVKuXz/x5g9Jbkn/G6cLLM1pi9Z8DAECSzNSutIZc/burm7iFbhixH7t804trQFFog0ROlDQH5wiXVq+4CFk5rRD1YZal0b5r8TfaYbro8Fp0ACEc5KZP48hi0iMERyef/PmPQpo15xQ1Xk5VF67VSeys3+f/xEDcIhq4oQJS+VF13NMbHxRlGtYfknAGVnm82Y1254dmhICmrQQh699cpGkhClwVUKOCLCM2v6UKJrke1JRuRj2hpI77plvtDWEtrplTRl0pwjdn8YS1fyE8r0APP4odALUlutifMHcMo7VGrPexfblwD7ksf/l2N+t3x50xo6K/8L6V1wPf76HO6TRGlNJuY6ovEP+KyX1TDzPvkiOlp8YFmy2LNLF67qQpLxHKWVWgyD+NLzZoA1wtkrofnuth7Be2szCNdLF/ODqLZe3XIMEfDn6u/EWpM1t9/Cqn9wfzm/O1WtJc4HNIbjH9D4PAT00edruAZpYjZIfZf2j0ZQdLU29nt5d0wDMT9iDfRBQwfStPnHAGVIx07dHViH/rMiYgG5a58Gxr/LRm8Zc16Akh3VagqPK+0fpCpjsMbLN0i5tNrrWbyx+3BurNIpiGeQ3TqLyxEJKcoAFCuJcNBcqpUprI5HLioseIPCPbcLU4E=
